version: '3'
services:
  ergo-node-1: &ergo-node-template
    image: bellsoft/liberica-openjdk-alpine
    restart: unless-stopped
    volumes:      
      - ./.ergo-1:/ergo/.ergo
      - ./config/ergo-1.conf:/app/ergo.conf
      - ./ergo-5.0.14.jar:/app/ergo.jar
    ports:
      - "9500:9053"
      - "9600:9030"
    working_dir: /app
    command: java -jar -Xmx2G ergo.jar --mainnet -c ergo.conf

  ergo-node-2:
    <<: *ergo-node-template
    volumes:      
      - ./.ergo-2:/ergo/.ergo
      - ./config/ergo-2.conf:/app/ergo.conf
      - ./ergo-5.0.14.jar:/app/ergo.jar
    ports:
      - "9501:9053"
      - "9601:9030"

  ergo-node-3:
    <<: *ergo-node-template
    volumes:      
      - ./.ergo-3:/ergo/.ergo
      - ./config/ergo-3.conf:/app/ergo.conf
      - ./ergo-5.0.14.jar:/app/ergo.jar
    ports:
      - "9502:9053"
      - "9602:9030"

  ergo-node-4:
    <<: *ergo-node-template
    volumes:      
      - ./.ergo-4:/ergo/.ergo
      - ./config/ergo-4.conf:/app/ergo.conf
      - ./ergo-5.0.14.jar:/app/ergo.jar
    ports:
      - "9503:9053"
      - "9603:9030"

  ergo-node-5:
    <<: *ergo-node-template
    volumes:      
      - ./.ergo-5:/ergo/.ergo
      - ./config/ergo-5.conf:/app/ergo.conf
      - ./ergo-5.0.14.jar:/app/ergo.jar
    ports:
      - "9504:9053"
      - "9604:9030"

  ergo-node-6:
    <<: *ergo-node-template
    volumes:      
      - ./.ergo-6:/ergo/.ergo
      - ./config/ergo-6.conf:/app/ergo.conf
      - ./ergo-5.0.14.jar:/app/ergo.jar
    ports:
      - "9505:9053"
      - "9605:9030"
