version: '3'
services:
  ergo-testnet-node:
    container_name: node-testnet
    image: bellsoft/liberica-openjdk-alpine
    restart: unless-stopped
    volumes:      
      - ./.ergo:/ergo/.ergo
      - ./ergo.conf:/app/ergo.conf
      - ./ergo-testnet-sync.jar:/app/ergo.jar
    ports:
      - 9052:9052
      - 9020:9020
    working_dir: /app
    command: java -jar -Xmx6G ergo.jar --testnet -c ergo.conf
